repos:
  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    # - id: flake8
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    # - id: check-added-large-files
    - id: pretty-format-json
      args: [--autofix]
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    - id: isort
      args: ["--profile", "black"]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.790
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports]
